/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ucloudlink_framework_remoteuim_SoftSimNative */

#ifndef _Included_com_ucloudlink_framework_remoteuim_SoftSimNative
#define _Included_com_ucloudlink_framework_remoteuim_SoftSimNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_SUCCESS
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_SUCCESS 0L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_PARAM_INVALID
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_PARAM_INVALID -1L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_ERROR
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_ERROR -101L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_UNKONW
#define com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_UNKONW 0L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_GSM
#define com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_GSM 1L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_UICC
#define com_ucloudlink_framework_remoteuim_SoftSimNative_MODE_SOFTSIM_UICC 2L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_CARD_VSIM
#define com_ucloudlink_framework_remoteuim_SoftSimNative_CARD_VSIM 0L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_CARD_SOFTSIM
#define com_ucloudlink_framework_remoteuim_SoftSimNative_CARD_SOFTSIM 1L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_EXIST
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_EXIST -102L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOEXIST
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOEXIST -103L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_INSERTED
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_INSERTED -104L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOINSERTED
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOINSERTED -105L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOSLOT
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOSLOT -106L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_POWERUP
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_POWERUP -107L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_POWERDOWN
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_POWERDOWN -108L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOKIPRESENT
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_CARD_NOKIPRESENT -109L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_NOTFOUND
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_NOTFOUND -120L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_OPENFAIL
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_OPENFAIL -121L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_UNZIPFAIL
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_UNZIPFAIL -122L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_PARSEFAIL
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_PARSEFAIL -123L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_PROTOCOL_INVALID
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_FILE_PROTOCOL_INVALID -124L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_OPLIMITED
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_OPLIMITED -140L
#undef com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_NOMEMORY
#define com_ucloudlink_framework_remoteuim_SoftSimNative_E_SOFTSIM_NOMEMORY -141L
/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    insertCard
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_insertCard
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    removeCard
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_removeCard
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    powerUp
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_powerUp
  (JNIEnv *, jobject, jint, jbyteArray, jintArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    powerDown
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_powerDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    resetCard
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_resetCard
  (JNIEnv *, jobject, jint, jbyteArray, jintArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    apdu
 * Signature: (I[B[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_apdu
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    queryCard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_queryCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    setDataPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_setDataPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    addCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_addCard__Ljava_lang_String_2Ljava_lang_String_2_3B_3B
  (JNIEnv *, jobject, jstring, jstring,jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    addCard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_addCard__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    deleteCard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_deleteCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    getCardCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_getCardCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    getCardList
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_getCardList
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    queryCardType
 * Signature: (Ljava/lang/String;[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_queryCardType
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    setDbPwd
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_setDbPwd
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    simImageQuery
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_simImageQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    getChallenge
 * Signature: ([B[I)V
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_getChallenge
  (JNIEnv *, jobject, jbyteArray, jintArray);

/*
 * Class:     com_ucloudlink_framework_remoteuim_SoftSimNative
 * Method:    challengeResult
 * Signature: ([BI)V
 */
JNIEXPORT jint JNICALL Java_com_ucloudlink_framework_remoteuim_SoftSimNative_challengeResult
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
